name: 'Build'

trigger:
- main

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

jobs:
- job: BuildWindows
  displayName: 'Windows Server 2022'
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET 6'
    inputs:
      packageType: sdk
      version: 6.0.400
  - task: NuGetAuthenticate@0
  - script: ./publish.cmd Release
    displayName: 'Build'
  - script: dotnet test --no-restore
    displayName: 'Test'

- job: BuildLinux
  strategy:
    matrix:
      'CentOS 8':
        containerImage: centos:8
      'CentOS 7':
        containerImage: centos:7
      'Debian 11':
        containerImage: mcr.microsoft.com/dotnet/sdk:6.0-bullseye-slim
      'Ubuntu 20':
        containerImage: mcr.microsoft.com/dotnet/sdk:6.0-focal

  displayName: Linux

  pool:
    vmImage: 'ubuntu-latest'

  container: $[ variables['containerImage'] ]

  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET 6'
    inputs:
      packageType: sdk
      version: 6.0.400
  - task: NuGetAuthenticate@0
  - script: ./publish.cmd Release
    displayName: 'Build'
  - script: dotnet test --no-restore
    displayName: 'Test'
