name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-macos:
    runs-on: ${{ matrix.os }}
    name: Build (${{ matrix.name }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-11
            name: MacOS 11
          - os: macos-12
            name: MacOS 12

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.401
    - name: Build
      run: ./publish.cmd Release
    - name: Test
      run: dotnet test --no-restore

  build-linux:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    name: Build (${{ matrix.name }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: fedora:35
            name: Fedora 35
          - container: fedora:36
            name: Fedora 36

    steps:
      - name: Install Prerequisites
        run: dnf makecache --refresh && dnf install -y findutils libicu
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.401
      - name: Build
        run: ./publish.cmd Release
      - name: Test
        run: dotnet test --no-restore
